name: example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  freezed: ^2.3.2
  build_runner: ^2.3.3
  flutter_localization: ^0.1.10
  intl: ^0.17.0
  data_table_2: ^2.4.2
  #hide app controlls
  bitsdojo_window: ^0.1.5
  jiffy: ^5.0.0
  window_manager: ^0.3.2
  dropdown_search: ^5.0.6
  textfield_search: ^0.10.0
  get_storage: ^2.1.1
  excel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  rename: ^2.1.1

flutter:
  uses-material-design: true